feat: add class linreg and scoring
SuSFCTV/NN-models pull request #1
Opened 2021-10-08 18:45 UTC by SuSFCTV

2021-10-08 21:57 UTC, ARQtty requested changes
удалить ненужные файлы

2021-10-08 21:57 UTC, ARQtty commented on .idea/.gitignore
> +# Default ignored files
.idea не пушат

2021-10-20 17:51 UTC, ARQtty requested changes
типы

2021-10-20 17:51 UTC, ARQtty commented on ml_sect/model.py
> +import numpy as np
__pycache__ не должно быть в итоговом репозитории

2021-10-20 17:51 UTC, ARQtty commented on ml_sect/model.py
> +    def fit(self, X, y):
типы

2021-10-20 17:51 UTC, ARQtty commented on ml_sect/model.py
> +    def fit(self, X, y):
тут и далее нужно проставить

2021-10-20 17:51 UTC, ARQtty commented on ml_sect/model.py
> +class MyGradientLinearRegression(MyLinearRegression):
1 класс - 1 файл

2021-10-20 17:51 UTC, ARQtty commented on ml_sect/model.py
> +        self.losses = []
стоит объявлять в конструкторе

2021-10-20 17:51 UTC, ARQtty commented on ml_sect/preparing_data.py
> +    return X, y
newline

2021-10-20 17:51 UTC, ARQtty commented on ml_sect/preparing_data.py
> +def prepare_df(df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
коммент о том что делает функция

2021-10-20 17:51 UTC, ARQtty commented on ml_sect/score_model.py
> +df = pd.read_csv('insurance.csv')
не должно быть кода без if __name__ == __main__

2021-10-30 21:01 UTC, ARQtty commented
хеллоу?

2021-11-05 19:06 UTC, ARQtty requested changes
доделать

2021-11-05 19:06 UTC, ARQtty commented on ml_sect/MyGradientLinearRegression.py
> +class MyGradientLinearRegression(MyLinearRegression):
нейминг ужасный

2021-11-05 19:06 UTC, ARQtty commented on ml_sect/MyGradientLinearRegression.py
> +from typing import List
файлы в питоне должны именоваться в snake_case. Почитай PEP8

2021-11-05 19:06 UTC, ARQtty commented on ml_sect/MyGradientLinearRegression.py
> +    def _calc_gradient(X: pd.DataFrame, y: pd.DataFrame, y_pred: pd.DataFrame) -> int:
метод возвращает не int. Ты тестировал код?

2021-11-05 19:06 UTC, ARQtty commented on ml_sect/MyLinearRegression.py
> +    def predict(self, X: pd.DataFrame):
тут вообще нет возвращаемых типов.

2021-11-05 19:06 UTC, ARQtty commented on ml_sect/MyLinearRegression.py
> +    def get_weights(self) -> pd.DataFrame:
Типы расставлены рандомно?

2021-11-05 19:06 UTC, ARQtty commented on ml_sect/preparing_data.py
> +def prepare_df(df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
где

2021-11-05 19:06 UTC, ARQtty commented on ml_sect/score_model.py
> +    df = pd.read_csv('insurance.csv')
хардкод - это плохо

2021-11-05 19:06 UTC, ARQtty commented on ml_sect/main.py
> +    score_model()
возможно ты хотел написать тесты. Но это не тесты

2021-11-05 19:11 UTC, SuSFCTV commented on ml_sect/score_model.py
> +    df = pd.read_csv('insurance.csv')
не оч понял, что ты имеешь в виду

2021-11-09 09:53 UTC, SuSFCTV commented on ml_sect/MyGradientLinearRegression.py
> +    def _calc_gradient(X: pd.DataFrame, y: pd.DataFrame, y_pred: pd.DataFrame) -> int:
либо даун я, либо пайчарм
![image](https://user-images.githubusercontent.com/48714345/140902166-47228fd5-08be-447f-bc38-dbcdd86d456b.png)

2021-11-09 09:56 UTC, SuSFCTV commented on ml_sect/MyGradientLinearRegression.py
> +    def _calc_gradient(X: pd.DataFrame, y: pd.DataFrame, y_pred: pd.DataFrame) -> int:
я даун

2021-11-09 22:45 UTC, ARQtty commented on ml_sect/gradient_linear_regression.py
> +class GradientLinearRegression(LinearRegression):
хороший нейминг

2021-11-09 22:48 UTC, ARQtty approved these changes
гуд

2021-11-09 22:48 UTC, ARQtty commented on ml_sect/gradient_linear_regression.py
> +        # Принимает на вход X, y и вычисляет веса по данной выборке
лучше на английском

2021-11-09 22:48 UTC, ARQtty commented on ml_sect/gradient_linear_regression.py
> +class GradientLinearRegression(LinearRegression):
хороший нейминг

2021-11-09 22:48 UTC, ARQtty commented on ml_sect/gradient_linear_regression.py
> +    def _calc_gradient(X: pd.DataFrame, y: pd.DataFrame, y_pred: pd.DataFrame) -> pd.DataFrame:
y скорее всего pd.Series, а не датафреймы

2021-11-09 22:48 UTC, ARQtty commented on ml_sect/test_linreg.py
> +class TestLinearRegression(unittest.TestCase):
восхитительно

2021-11-09 23:08 UTC, merged